# Generated by Django 5.2.7 on 2026-02-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(max_length=30)),
                ('license_expiry', models.DateField()),
                ('safety_score', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_id', models.IntegerField()),
                ('expense_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('expense_date', models.DateField()),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FuelLogs',
            fields=[
                ('fuel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_id', models.IntegerField()),
                ('trip_id', models.IntegerField()),
                ('liters', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('fuel_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLogs',
            fields=[
                ('maintenance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_id', models.IntegerField()),
                ('service_type', models.CharField(max_length=100)),
                ('service_date', models.DateField()),
                ('next_service_due', models.DateField()),
                ('cost', models.IntegerField()),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trip_id', models.IntegerField()),
                ('revenue_amount', models.IntegerField()),
                ('received_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('cargo_weight', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_odometer', models.IntegerField()),
                ('end_odometer', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('max_capacity_kg', models.IntegerField()),
                ('odometer', models.IntegerField()),
                ('acquisition_cost', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
